name: "Release"

on:
  workflow_call:
    secrets:
      PRIVATE_REPO_CLONING_TOKEN:
        description: "Cloning token"
        required: true

jobs:
  create-release:
    runs-on: self-hosted
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          path: ./artifacts
          merge-multiple: true

      - name: Create GitHub release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            ./artifacts/Defguard.ipa
            ./artifacts/app-release.aab
            ./artifacts/app-release.apk

  create-sbom:
    needs: [create-release]
    uses: ./.github/workflows/sbom.yaml
    with:
      upload_url: ${{ needs.create-release.outputs.upload_url }}
    secrets:
      PRIVATE_REPO_CLONING_TOKEN: ${{ secrets.PRIVATE_REPO_CLONING_TOKEN }}

